### ISSUE TITLE
Move to the Dockstore or related GitHub Organization

### ISSUE THREAD

**Issue by mr-c** [dockstore/cwlavro#24]
Hey @denis-yuen 

I think you all are the only users of this library, and now that cwljava is revived we should probably transfer the repository to you all.

What do you think? Where would you like it to go?

**Comment by denis-yuen** [comment]
Hi,
Don't have a strong opinion, we'll probably be maintaining this for at least the near future. (haven't had much of a chance to look through cwljava and new developments in schema salad). 

https://github.com/common-workflow-lab seems to make sense as well ("Experimental, unofficial, repositories of CWL community members") as long as we have access

**Comment by mr-c** [comment]
@denis-yuen If I make you the owner, then you can move it to https://github.com/dockstore ; would that be okay?

**Comment by mr-c** [comment]
@denis-yuen Any update on this?

**Comment by denis-yuen** [comment]
Hmmm, might have missed a notification. But it doesn't look like I have permissions to move 
![Screenshot from 2021-03-17 10-07-59](https://user-images.githubusercontent.com/1730679/111480854-cafd0600-8708-11eb-8582-d252d0fcc6da.png)

**Comment by mr-c** [comment]
@denis-yuen Try again?

**Comment by denis-yuen** [comment]
Moved!

**Comment by mr-c** [comment]
Thank you @denis-yuen  ; enjoy!
